TRAIN:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 32
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: True
DATA:
  INPUT_CHANNEL_NUM: [1, 1]
AUDIO_DATA:
  CLIP_SECS: 1.999
  NUM_FRAMES: 400
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  FREQUENCY_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  FREQUENCY_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
BN:
  USE_PRECISE_STATS: True
  FREEZE: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 25]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: -1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: [97, 300]
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: epickitchens
  BATCH_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
EPIC2020:
  TRAIN_PLUS_VAL: False
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
